name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  TTY_COMPATIBLE: 1

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1
      - name: Build and Test Arachne
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          cache: true
          activate-environment: false
      - run: pixi run build
      - run: test/data.py
      - run: bin/arachne index test/hap1.fa
      - run: bin/arachne align -t 4 -s TestSample test/hap1.fa test/test.R{1,2}.fq.gz
